### ISSUE TITLE
 Could not find pre-processed datasets 

### ISSUE THREAD

**Issue by cylinbao** [RUC-NLPIR/FlashRAG#1]
Hi Thanks for the great work!!

In the README, it mentions that you have collected and processed 35 common used datasets such as NQ, TrivaQA, etc..
However, I could not find where I can download access those preprocessed datasets from this repo.
I'm not sure if I miss anything in the document or the codebase.
Can you provide some guidance? Thanks.

**Comment by DaoD** [comment]
Hi,

All datasets are provided in Huggingface datasets.

https://huggingface.co/datasets/ignore/FlashRAG_datasets

Regards,
Yutao

**Comment by cylinbao** [comment]
Got it. Thank you!

**Comment by cylinbao** [comment]
Hi I also wonder do you have the preprocessed wiki dump and index that are used in your experiments available?

I tried to test FlashRAG with my wiki dump from wiki_dpr and index with contriever. However, the accuracy I got from some of your baselines(zero-shot, naive, iter-gen) are lower than the reported numbers. I suspect it might be the misalignment of the data source and index. Therefore, it will be really helpful if you can provide the preprocessed wiki dump and index. I know we can replicate by following [this](https://github.com/RUC-NLPIR/FlashRAG/blob/main/docs/process-wiki.md), but it seems taking a long time to run.
