### ISSUE TITLE
Question about knowledge source

### ISSUE THREAD

**Issue by XMHZZ** [RUC-NLPIR/FlashRAG#10]
Hi Team,

I'm wondering if all the Wiki-based tasks use the December 2018 snapshot (~20M 100-word passages from the DPR paper). 
For example, HotPotQA usually only uses the first paragraph of each Wikipedia page from a 2017 version.

Thanks!

**Comment by ignorejjj** [comment]
Hi, our current results are all using the dpr version of wiki dump you mentioned. 

Do you mean we need more ways to process the wiki (such as only retain first paragraph)?

**Comment by ignorejjj** [comment]
We have aligned our settings and used the same retrieval document for various methods.
