### ISSUE TITLE
Questions about dataset and reranker

### ISSUE THREAD

**Issue by YANthinkn** [RUC-NLPIR/FlashRAG#105]
Hi,

FlashRAG provides many processed benchmark datasets on [huggingface datasets](https://huggingface.co/datasets/RUC-NLPIR/FlashRAG_datasets) for use. 
However, only `nq`, `quartz` or some other datasets have `test.jsonl` file, while I want to test on `2wikimultihopqa` or `musique`. Will you provide the related test dataset in the future?

Meanwhile, I am testing the influence of rerankers on the model's performance. So, I may place emphasis on the order of retrieved documents before and after the reranking process. Does FlashRAG provide the function or parameter to output the documents' orders? If not, I could modify the FlashRAG framework by myself. But could you provide some suggestions on where I should modify it?

Thank you!

**Comment by ignorejjj** [comment]
A simple way is to run the experiment twice with and without reranker, respectively. Then compare the retrieval results from the two experiments. 

If you have other requirements, you can modify `FlashRAG/flashrag/retriever/retriever.py`. You can modifying the interface of  `wrapper` function in `rerank_manager` to return the original document.

**Comment by YANthinkn** [comment]
> A simple way is to run the experiment twice with and without reranker, respectively. Then compare the retrieval results from the two experiments.
> 
> If you have other requirements, you can modify . You can modifying the interface of function in to return the original document.`FlashRAG/flashrag/retriever/retriever.py``wrapper``rerank_manager`

I want to see the detailed differences instead of the general result, so I may just modify the function. Thank you for providing the exact function I need to change!

**Comment by YANthinkn** [comment]
Hi, I am sorry that I have to ask some stupid questions again, since I am not so familiar with FlashRAG framework. 

I noticed that Sequential Pipeline implements a linear execution path for the query, formally represented as query-> retriever -> post-retrieval (reranker, refiner) -> generator. 

But could FlashRAG support the workflow like: only one query -> retriever -> post-retrieval (reranker, refiner) -> generator -> next query -> retriever -> post-retrieval (reranker, refiner) -> generator…? 

Thank you !

**Comment by ignorejjj** [comment]
At present, the process you described is not implemented in flashrag, which actually involves a lot of customization (such as how to get the next query from generate). 

But there are currently supported pipelines that are quite similar to what you mentioned: `IRCotPipeline, FlAREPPipeline`. You can refer to the corresponding paper to see if it meets your needs.

You can also easily build one pipeline by concatenating the input and output of the retriever and generator. I recommend you refer to the writing style of the run function in `SequentialPipeline`.

If you have any questions in building your pipeline, feel free to ask me.

**Comment by YANthinkn** [comment]
> At present, the process you described is not implemented in flashrag, which actually involves a lot of customization (such as how to get the next query from generate).
> 
> But there are currently supported pipelines that are quite similar to what you mentioned: `IRCotPipeline, FlAREPPipeline`. You can refer to the corresponding paper to see if it meets your needs.
> 
> You can also easily build one pipeline by concatenating the input and output of the retriever and generator. I recommend you refer to the writing style of the run function in `SequentialPipeline`.
> 
> If you have any questions in building your pipeline, feel free to ask me.

Thank you. Actually, I am now exploring the effect of reranker, also using metrics to evaluate it.  For example, I want to see the top10 retrieval results before and after using the reranker. However, after modifying the interface of the wrapper function in rerank_manager, it seems that it could only give the top1 result. Could you give me some tips on how to get the result I want?
