### ISSUE TITLE
请问如果不使用gpu应该如何修改配置或代码

### ISSUE THREAD

**Issue by githubyounik** [RUC-NLPIR/FlashRAG#106]
我发现默认的配置中gpu_id: "0,1,2,3"，我希望在不使用gpu的情况下调用代码，请问需要怎么修改配置。
文件FlashRAG\flashrag\generator\generator.py第528行只有gpu数量不等于1和等于1两种情况，没有gpu似乎与多gpu划分为同种情况进行处理。

**Comment by ignorejjj** [comment]
528行对应的是FastChatGenerator，默认会用到gpu。如果想只用cpu，可以使用HFCausalLMGenerator，需要将config里面的`gpu_id`设置为`None`, `framework`设置为`hf`
