### ISSUE TITLE
6个数据集上13种RAG方法的评测代码

### ISSUE THREAD

**Issue by NLPerWS** [RUC-NLPIR/FlashRAG#16]
您好，能够提供下在6个数据集上13种RAG方法的评测代码？

**Comment by ignorejjj** [comment]
你好， [代码脚本](../blob/main/examples/methods/run_exp.py)以及相关的配置文件已经在我们的仓库中提供。只需要修改对应的数据集即可跑出多个结果。

后续我们将会补充给出说明文档来对评测过程进行具体说明。
