### ISSUE TITLE
windows安装不上pyserini

### ISSUE THREAD

**Issue by yanqiangmiffy** [RUC-NLPIR/FlashRAG#18]
note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for nmslib
  Running setup.py clean for nmslib
Failed to build nmslib

**Comment by ignorejjj** [comment]
你好，pyserini的安装问题我们无法提供帮助，可以去pyserini的issue下面进行提问。

如果不考虑使用bm25作为检索器，也可以不安装pyserini (直接将requirement.txt中的对应代码注释即可)。
