### ISSUE TITLE
和paper对齐测试结果

### ISSUE THREAD

**Issue by ypw-lbj** [RUC-NLPIR/FlashRAG#29]
您好！
    首先感谢FlashRAG这个开源工作。对本工作比较感兴趣，在复习paper中的结果，有几个问题如下：
    1) 6个测试集中只有部分包含test.jsonl， 论文中的测试集是针对test？ 还是train+test+dev？或者其他设置？
    2) 论文Table3的实验，采用LLAMA3-8B-instruct、E5-base-v2、Wiki语料库 ?
    3) 其它参数：retrieval_topk、rerank_topk、generation_params等只需要和提供“examples/methods/my_config.yaml”保持一致即可？
    4) 另外，对齐论文结果还需要注意哪些环节？
谢谢！

**Comment by ignorejjj** [comment]
感谢你对我们工作的关注！

针对实验结果的复现，我们提供了两个文档供参考: [复现实验的指南](../blob/main/docs/reproduce_experiment.md)以及[实验中的参数细节设置](blob/main/docs/baseline_details.md)。但很抱歉在里面漏掉了数据集的设置，我们稍后会进行补充。

对于你提出的问题:

1. 数据集的使用: 对于有test集的数据集，我们都使用test集合进行测试，否则使用dev集进行测试(也就是nq,tqa,popqa,webq是test，其余是dev)。表格中的所有结果使用了每个数据集的前1000条数据 (在config里面设置`test_sample_num`为1000，并关闭`random_sample`)。我们在全量数据集上进行过测试，与1000条数据的结果相差较小。
2. 使用的模型在两个文档中列出。使用的是llama3-8B-instruct+E5, wiki语料库是我们dataset中提供的版本
3. 涉及的其他参数也已经在文档中列出，其他参数只需要和`my_config.yaml`即可
4.  推荐使用vllm框架进行实现，速度较快 (但是replug目前不支持使用vllm)。
