### ISSUE TITLE
How can I build AAR-ANCE index?

### ISSUE THREAD

**Issue by Ciao-CA** [RUC-NLPIR/FlashRAG#32]
when I run index_builder.py，I got an error
`ValueError: You have to specify either decoder_input_ids or decoder_inputs_embeds`
I guess it may due to ANCE's T5 based(encoder-decoder), and I don't find where decoder is in index_builder.py.
So I wonder how I can solve this question, thanks!
![ance](https://github.com/RUC-NLPIR/FlashRAG/assets/56443448/32e95387-4a16-42a0-9ccc-9260c613e573)

**Comment by ignorejjj** [comment]
Sorry, there is a bug when determining the model type in multi gpu setting, which may result in inability to properly recognize T5-based models. 

We have fixed it, you can try it again.

Note: For ANCE, you should set `pooling_method` to `cls`.
