### ISSUE TITLE
introduction_for_beginners中出现错误

### ISSUE THREAD

**Issue by snow163** [RUC-NLPIR/FlashRAG#33]
![1](https://github.com/RUC-NLPIR/FlashRAG/assets/145819348/fca52f20-8fe5-493a-a71b-9f95e6983960)
非常感谢您的工作，但是我在接触的时候出现RuntimeError: probability tensor contains either `inf`, `nan` or element < 0错误，请问应该怎么解决？

**Comment by ignorejjj** [comment]
在推理时涉及的token采样可能会出现这种问题。可以在`generation_params`中将`do_sample`设置为`False`。
![image](https://github.com/RUC-NLPIR/FlashRAG/assets/55341185/e511cc73-a1d1-4668-8025-c641245bf9f1)
