### ISSUE TITLE
完整运行所需要的配置

### ISSUE THREAD

**Issue by snow163** [RUC-NLPIR/FlashRAG#38]
首先，感谢您工作的分享和每次及时的解答。

我想询问一下，如果想完整运行您这个项目，需要什么配置？内存大小，数据盘大小，GPU等等。

因为我是在autodl上租服务器运行的，配置可能选的不高，在构建索引时，出现了程序killed，看监控应该是我选的90G的内存不够。所以想向您询问一下配置。

**Comment by ignorejjj** [comment]
你好， 硬盘内存最好在150G以上(索引~80G，检索文档~20G，模型~30G)，GPU最好单卡显存35G以上，机器内存最好50G以上。
如果需要的话，后续我们可以考虑将索引上传到托管平台上方便直接下载。

**Comment by snow163** [comment]
如果方便的话，请将索引上传到托管平台上，方便直接下载。感谢。

**Comment by ignorejjj** [comment]
已上传: https://huggingface.co/datasets/ignore/FlashRAG_datasets/tree/main/retrieval-corpus
