### ISSUE TITLE
复现论文结果遇到的一些问题

### ISSUE THREAD

**Issue by LiyiLily** [RUC-NLPIR/FlashRAG#40]
首先感谢作者开源代码，便于对不同方法的公平比较。最近我在尝试运行“FlashRAG/examples/methods/run_exp.py”文件，部分方法根据指南可以直接、或简单修改后运行成功，以下方法遇到一些问题希望可以帮助解答：

1. LongLLMLingua  和  RECOMP-abstractive  方法out of memory，多次运行发现该问题出现的时间不固定，有时是在加载模型时、有时可以顺利加载模型但在Processed prompts时又报错。我的实验环境用的4张24G的4090，不清楚是不是该硬件环境不支持。

2. Ret-Robust和flare运行报错
Ret-Robust报错如下：
![image](https://github.com/RUC-NLPIR/FlashRAG/assets/29744135/00b343e5-6c11-4290-91da-801026cf17e2)

flare报错如下：
![image](https://github.com/RUC-NLPIR/FlashRAG/assets/29744135/64ff6370-3b74-424c-89b8-0ab05757a36d)

查看发现，检索返回的doc_item是字典组成的列表，而不是单一字典

3. REPLUG 运行报错，参数异常
![image](https://github.com/RUC-NLPIR/FlashRAG/assets/29744135/6e67e4b6-eb28-4331-9e16-99fd6cf4c47f)
branching_pipeline.py  line 19：self.generator = get_generator(config, model=model)
而 VLLMGenerator 中 只声明了config，缺少参数model

**Comment by ignorejjj** [comment]
你好, 感谢对我们工作的关注。
1.  LongLLMLingua和RECOMP需要额外运行一个模型，会占用部分显存，可能会导致generator生成的时候出现显存不足的情况。我们更新了代码，在用完refiner之后直接进行删除，释放占用的显存，应该能解决这个问题。(see 590516875421254b08656562895a6426d76ce2a9)
2. 使用的貌似是旧代码，更新成最新代码就行
3. replug要修改generator生成logit的逻辑，暂时不支持使用vllm框架，可以换成

**Comment by LiyiLily** [comment]
@ignorejjj 感谢您的回复，我已下载最新版本代码，但之前的问题仍然存在。

**Comment by ignorejjj** [comment]
你好，感谢提出的问题。我在最新的代码上进行了一些实验:
1. longllmlingua使用的摘要模型和generator模型一起运行会占用约30G显存. 我对代码逻辑进行了优化，使用完refiner之后再加载generator，显存占用可以控制在18G左右，拉取最新代码应该可以实现
2. 我在各种设置下测试了一下flare和ret-robust两种方法，均能正确运行。如果仍然有问题，能否贴出代码片段方便定位问题。
3. replug使用的是fschat框架
4. 抱歉这里表述有点重复，standard rag对应naive，naive对应zero-shot
5. 如果是方法中普遍的结果比论文汇报的低，请检查下面几个方面是否一致: 
(1) 检索的文档使用的是我们在huggingface仓库提供的文档，建立index时max_length设置为512，并开启了fp16。
(2) 生成模型设置do_sample=False
(3) 测试数据选取的是前1000条数据，没有开启`random_sample`
(4) 可以尝试分别使用vllm和fschat两个框架进行测试，不同机器上这两个结果可能有差异

如果仍然有问题，可以将`intermediate_data.json`以及`config.yaml`发我邮箱来具体看一下差异(邮箱： jinjiajie@ruc.edu.cn）

**Comment by lv-dot** [comment]
![Uploading 1720518090501.png…]()

**Comment by ignorejjj** [comment]
上面的问题是由于intermediate data中存在numpy类型的数据导致的，我们已经修复了这个问题: 98401bba9fd402d4c7372f75650a432402cffed5。

**Comment by WellWang-S** [comment]
> 你好，感谢提出的问题。我在最新的代码上进行了一些实验:
> 
> 1. longllmlingua使用的摘要模型和generator模型一起运行会占用约30G显存. 我对代码逻辑进行了优化，使用完refiner之后再加载generator，显存占用可以控制在18G左右，拉取最新代码应该可以实现
> 2. 我在各种设置下测试了一下flare和ret-robust两种方法，均能正确运行。如果仍然有问题，能否贴出代码片段方便定位问题。
> 3. replug使用的是fschat框架
> 4. 抱歉这里表述有点重复，standard rag对应naive，naive对应zero-shot
> 5. 如果是方法中普遍的结果比论文汇报的低，请检查下面几个方面是否一致:
>    (1) 检索的文档使用的是我们在huggingface仓库提供的文档，建立index时max_length设置为512，并开启了fp16。
>    (2) 生成模型设置do_sample=False
>    (3) 测试数据选取的是前1000条数据，没有开启`random_sample`
>    (4) 可以尝试分别使用vllm和fschat两个框架进行测试，不同机器上这两个结果可能有差异
> 
> 如果仍然有问题，可以将`intermediate_data.json`以及`config.yaml`发我邮箱来具体看一下差异(邮箱： [jinjiajie@ruc.edu.cn](mailto:jinjiajie@ruc.edu.cn)）
复现出来和论文结果差别很大，ret-robust的index_path和corpus_path是什么，是需要针对数据集重新构造还是什么特殊处理，hotpotqa的build_index一直有问题

**Comment by ignorejjj** [comment]
@WellWang-S 除了AAR，其他所有方法的index和corpus都是一样的，不需要针对数据集进行特殊处理。其他必要的设置请参考复现实验的[说明文档](https://github.com/RUC-NLPIR/FlashRAG/blob/main/docs/reproduce_experiment.md)

**Comment by WellWang-S** [comment]
> @WellWang-S 除了AAR，其他所有方法的index和corpus都是一样的，不需要针对数据集进行特殊处理。其他必要的设置请参考复现实验的[说明文档](https://github.com/RUC-NLPIR/FlashRAG/blob/main/docs/reproduce_experiment.md)

@ignorejjj 说明文档看了，这俩参数实际没啥影响，用quick start的index_path和corpus_path即可，但是实验结果和论文结果差了10个点

**Comment by ignorejjj** [comment]
说明文档里面有写，用的不是quick start的index和corpus，要自己重新建index。
