### ISSUE TITLE
评估指标可否加上acc

### ISSUE THREAD

**Issue by snow163** [RUC-NLPIR/FlashRAG#47]
十分感谢您的工作，我看很多论文中都使用了acc这个指标，为了更好的比对，可否加入这个评估指标？

**Comment by ignorejjj** [comment]
我们代码里面的sub_em其实就是acc


---- 回复的原邮件 ----
发件人  ***@***.***> 日期  2024年07月04日 14:35 收件人  ***@***.***> 抄送至  ***@***.***> 主题  [RUC-NLPIR/FlashRAG] 评估指标可否加上acc (Issue #47)  

十分感谢您的工作，我看很多论文中都使用了acc这个指标，为了更好的比对，可否加入这个评估指标？
