### ISSUE TITLE
跑出来的结果很差，怎么提升效果，语料库还是换参数量大的模型

### ISSUE THREAD

**Issue by snow163** [RUC-NLPIR/FlashRAG#48]
连续四条的结果
![1](https://github.com/RUC-NLPIR/FlashRAG/assets/145819348/eba960ed-c812-498d-908b-59d34f9ac4d7)
![2](https://github.com/RUC-NLPIR/FlashRAG/assets/145819348/dafcda2b-5ba7-4104-a411-7458e6eeedd0)
![3](https://github.com/RUC-NLPIR/FlashRAG/assets/145819348/e6c86884-e68d-4857-b32b-bf6393795aff)
![4](https://github.com/RUC-NLPIR/FlashRAG/assets/145819348/45738667-98a3-470a-aefc-ba9e1af333a1)

**Comment by ignorejjj** [comment]
具体设置能否提供一下？

最好是用7B以上的模型

**Comment by ignorejjj** [comment]
可以先尝试跑完1000条数据之后看看指标能否与论文里的结果对齐。前四条数据答不对比较正常。

**Comment by snow163** [comment]
后面会将gpt等非开源模型集成上去吗？很多论文都是使用gpt3.5作为生成器。

**Comment by ignorejjj** [comment]
现在已经集成了openai的接口。参考[basic_config.yaml](https://github.com/RUC-NLPIR/FlashRAG/blob/main/flashrag/config/basic_config.yaml)中的设置，把`framework`设置为`openai`，`generator_model`设置为对应的模型名称，并设置`openai_setting`即可。
·
