### ISSUE TITLE
Only Available on Linux?

### ISSUE THREAD

**Issue by AldousShou** [RUC-NLPIR/FlashRAG#5]
I tried to install it on my apple silicon mac, but I ran into issue:

> AssertionError: vLLM only supports Linux platform (including WSL).

How should I solve the problem?

Thx for you help!

**Comment by ignorejjj** [comment]
It seems that vllm does not support mac yet.   

You can delete `vllm` from `requirement.txt` and check if other packages can be installed properly. If all other packages support Mac and can be installed normally, you can use other generators besides vllm (e.g. fastchat, hf).
