### ISSUE TITLE
如何将现有的一批扫描版pdf书籍，转化为FlashRAG所需要的Document Collection

### ISSUE THREAD

**Issue by RicoJYang** [RUC-NLPIR/FlashRAG#50]
是否可以提供一个参考的流程，非常感谢！

**Comment by ignorejjj** [comment]
FlashRAG目前没有对pdf进行处理的相关功能。你可以先使用一些开源工具将pdf转换成markdown或者txt格式，然后再处理成FlashRAG所需要的`.jsonl`格式。

参考的pdf转换工具: [PDF Converter](https://github.com/houking-can/PDFConverter),
