### ISSUE TITLE
gated repo (model)

### ISSUE THREAD

**Issue by codecodebear** [RUC-NLPIR/FlashRAG#51]
What are ways (interfaces) where config is able to directly connecting with HuggingFace such that we don't need to download models or the code can automatically download models for us?
For example, if I just use ```'model2path': {'e5': 'intfloat/e5-base-v2', 'llama3-8B-instruct': 'meta-llama/Meta-Llama-3-8B-Instruct'},``` in ```config_dict```, I get the following error for gated repo:
```
OSError: You are trying to access a gated repo.
Make sure to have access to it at https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct.
```
Right now, I have to manually download models and point to its directory when running in Google Colab, which is inconvenience.

**Comment by ignorejjj** [comment]
Our library supports direct connection with huggingface. But to download models that require permissions, you need to login first.

```python
from huggingface_hub import login
login()
```
