### ISSUE TITLE
Datasets里面提供的Huggingface datasets链接404打不开呀

### ISSUE THREAD

**Issue by majiangmqjiangma** [RUC-NLPIR/FlashRAG#53]
Datasets里面提供的Huggingface datasets链接404怎么打不开了呀，之前还是能用的。

**Comment by DaoD** [comment]
稍等，我们检查一下问题

**Comment by DaoD** [comment]
@majiangmqjiangma 由于huggingface不可知的原因，原链接失效，已重新更新链接为https://huggingface.co/datasets/RUC-NLPIR/FlashRAG_datasets，目前数据集仍在上传中
