### ISSUE TITLE
按照步骤不能正常运行

### ISSUE THREAD

**Issue by WangXuCh** [RUC-NLPIR/FlashRAG#54]
按照英文界面的操作，我修改了模型，用的是qwen1.5-7n-chat，然后用python simple_pipeline.py运行，报错如下：
OSError: Not enough disk space. Needed: Unknown size (download: Unknown size, generated: Unknown size, post-processed: Unknown size)

**Comment by DaoD** [comment]
OSError: Not enough disk space.
你的磁盘空间不足

**Comment by WangXuCh** [comment]
> OSError: Not enough disk space. 你的磁盘空间不足

磁盘空间有的，很充足

**Comment by DaoD** [comment]
这是os error，是您系统返回的错误，可能的原因是该模型下载的路径磁盘空间不足，我们这边无法复现该问题，也无法帮您处理，实在抱歉

**Comment by WangXuCh** [comment]
> 这是os error，是您系统返回的错误，可能的原因是该模型下载的路径磁盘空间不足，我们这边无法复现该问题，也无法帮您处理，实在抱歉

欧克欧克，我换个机器试一下，这个报错是在docker里面的
