### ISSUE TITLE
Killing local vLLM worker processes 

### ISSUE THREAD

**Issue by zzczzc666** [RUC-NLPIR/FlashRAG#56]
INFO 07-19 11:07:56 multiproc_worker_utils.py:123] Killing local vLLM worker processes
Fatal Python error: _enter_buffered_busy: could not acquire lock for <_io.BufferedWriter name='<stdout>'> at interpreter shutdown, possibly due to daemon threads
Python runtime state: finalizing (tstate=0x00000000014c29c0)

Current thread 0x00007fd701a06740 (most recent call first):
  <no Python frame>
我想请问一下出现这个错误，是我配置的原因吗（我使用的两个L20）还是我的参数设置太大了

**Comment by ignorejjj** [comment]
这应该是vllm本身的问题，可能是环境没配置好导致的，我们无法解决。可以尝试使用其他的framework(比如fastchat)。

**Comment by zzczzc666** [comment]
> 这应该是vllm本身的问题，可能是环境没配置好导致的，我们无法解决。可以尝试使用其他的framework(比如fastchat)。

ok,感谢您
