### ISSUE TITLE
accuracy of replicating EM for NQ using naive rag and selective-context

### ISSUE THREAD

**Issue by codecodebear** [RUC-NLPIR/FlashRAG#60]
Hello, I tried to replicate the EM score shown in [table](https://github.com/RUC-NLPIR/FlashRAG?tab=readme-ov-file#robot-supporting-methods). I am using ```NQ``` dataset.
For naive rag, I get an EM score of ```33.2``` which is lower than ```35.1``` as in the table. Do you think it is within reasonable range? If not, what are some reasons that may cause this issue and some suggestions to fix it?
full naive metric scores below:
```
em: 0.33240997229916897
f1: 0.4503892478844922
acc: 0.509972299168975
precision: 0.43761323716369915
recall: 0.5675530932594645
```

I also tried to run the ```selective-context``` approach, I get an EM score of 30.19 which is pretty similar to 30.5 in the table.
full selective-context approach metric scores below:
```
em: 0.30193905817174516
f1: 0.4159835191696627
acc: 0.42382271468144045
precision: 0.4148688047110833
recall: 0.4894921514312096
```

updates:
I am using the below command to build the index:
```
python -m flashrag.retriever.index_builder \
    --retrieval_method e5 \
    --model_path /home/smalldog/e5-base-v2 \
    --corpus_path /home/smalldog/wiki_dump/wiki_dump.jsonl \
    --save_dir /home/smalldog/wiki_dump/ \
    --use_fp16 \
    --max_length 200 \
    --batch_size 4096 \
    --pooling_method mean \
    --faiss_type Flat 
```
one reason I could think of is the ```max_length``` attribute, I set it to 200, which maybe small to incorporate longer-context docs, so some information might be lost here.

Thank you!

**Comment by ignorejjj** [comment]
I think your result is within the normal range. But my experiment was conducted at a longer max length (256), you can try increasing it a bit, the result may increase slightly.
