### ISSUE TITLE
how to speed up the refining process for selective context?

### ISSUE THREAD

**Issue by codecodebear** [RUC-NLPIR/FlashRAG#61]
Hi,

I tried to run the selective context approach on 1 GPU and 4 GPUs respectively, but the ```refining process``` takes the same amount of time (~18 min). GPU memory both stays very low. 
```
python run_exp.py --method_name 'selective-context' \
                  --split 'test' \
                  --dataset_name 'nq' \
                  --gpu_id '0,1,2,3'
```
Is there a way I can control to speed up this refining process (I don't see any parameters I can modify in refiner settings in config)? 

ps: the retrieval and generating process both take ~2 min and I am using conda env (so I think I have set up the repo correctly).

Thank you in advance for your help!

**Comment by ignorejjj** [comment]
Sorry, due to the native implementation of these two methods, the refiner accept one piece of data at a time for refinement (instead of batch). This will result in very slow execution speed. We have identified this issue, but have not yet found a good solution.
