### ISSUE TITLE
error in metrics scores for naive QA

### ISSUE THREAD

**Issue by codecodebear** [RUC-NLPIR/FlashRAG#63]
Hi,
I tried to run the naive QA datasets like NQ, but get this error when generating metric scores.
```
Error in em!
list indices must be integers or slices, not str
Error in f1!
list indices must be integers or slices, not str
Error in acc!
list indices must be integers or slices, not str
Error in precision!
list indices must be integers or slices, not str
Error in recall!
list indices must be integers or slices, not str
{}
```
updates: I think [self.choices](https://github.com/RUC-NLPIR/FlashRAG/blob/main/flashrag/evaluator/metrics.py#L33) is a list of empty lists right now.

Can you take a look? Thank you in advance!

**Comment by ignorejjj** [comment]
Sorry, there is a small issue here that we have fixed.
