### ISSUE TITLE
检索语料库的读取问题

### ISSUE THREAD

**Issue by yu-4041** [RUC-NLPIR/FlashRAG#65]
作者您好，首先感谢您的劳动成果的共享。

我在读取您共享的语料库时遇到了问题，具体问题如下：
我编写的读取代码为
![image](https://github.com/user-attachments/assets/c0f6a6fc-8df7-4962-bcbb-6707eef4b088)

使用utf-8编码读取时报错，
![image](https://github.com/user-attachments/assets/becb6d4a-fd1b-4609-b0cc-dab6fbf43843)
在使用latin-1 或 ISO-8859-1 时报错：
![image](https://github.com/user-attachments/assets/8eb625ec-e1b4-4194-9ce6-fbcc2b693914)

我已经重试多次重新下载和解压数据集，但仍然无法读取，我应该如何读取查看检索语料库的内容？

**Comment by yu-4041** [comment]
问题以解决，原因是因为解压的时候，文件第一行会有一些文件信息，在windows上换了一种解压格式，可以正常读取了。
再次感谢作者的无私分享和贡献

**Comment by ke-01** [comment]
> 问题以解决，原因是因为解压的时候，文件第一行会有一些文件信息，在windows上换了一种解压格式，可以正常读取了。 再次感谢作者的无私分享和贡献

我在linux上使用gunzip解压后，遇到了同样的问题，请问您是怎么解决的呢？
