### ISSUE TITLE
cannot access retrieval-corpus download link

### ISSUE THREAD

**Issue by oneonlee** [RUC-NLPIR/FlashRAG#69]
I cannot access a processd retrieval-corpus download link that you provided.
(https://huggingface.co/datasets/ignore/FlashRAG_datasets/tree/main/retrieval-corpus)
When I try to access the link, I got a 404 error.

Can you check and provide a new link?
Thanks.

**Comment by codecodebear** [comment]
As mentioned in changelog: 
https://huggingface.co/datasets/RUC-NLPIR/FlashRAG_datasets/tree/main/retrieval-corpus

**Comment by oneonlee** [comment]
I missed it. 

The new link hasn't been applied in `[docs/process-wiki.md](https://github.com/RUC-NLPIR/FlashRAG/blob/b075fe7a29b7c734723fda27d1e3e08325ea1af9/docs/process-wiki.md)`, so I think it needs to be updated.
