### ISSUE TITLE
assert d == self.d AssertionError

### ISSUE THREAD

**Issue by carolsos** [RUC-NLPIR/FlashRAG#73]
File "/hpc2hdd/home/.conda/envs/faiss-gpu/lib/python3.12/site-packages/faiss/class_wrappers.py", line 329, in replacement_search
    assert d == self.d
AssertionError

按照步骤，已经安装好faiss-gpu 1.8.0和python3.12，在运行python simple_pipeline.py     --model_path=/hpc2hdd/home/Qwen1.5-14B-Chat     --retriever_path=/hpc2hdd/home/bge-large-zh-v1.5命令时抛出以上错误，请问一下这个是数据出现了问题嘛？还是faiss-gpu包的问题啊？

**Comment by ignorejjj** [comment]
`simple_pipeline.py`使用的默认index的文件是用e5模型建的，因此要需要输入e5模型的路径。用bge会出现维度不匹配。

**Comment by carolsos** [comment]
哦哦，好的，谢谢❤️
