### ISSUE TITLE
如何使用rerank类型的模型

### ISSUE THREAD

**Issue by lifelsl** [RUC-NLPIR/FlashRAG#76]
你好，我想在RAG的流程中当检索完之后再加一个rerank，这个时候该怎么去做

**Comment by ignorejjj** [comment]
在`config.yaml`里面把`use_reranker`设置为`True`，然后填上对应的reranker路径即可。具体可以参考:https://github.com/RUC-NLPIR/FlashRAG/blob/main/flashrag/config/basic_config.yaml 中对应的参数。
