### ISSUE TITLE
请问generate怎么与class REPLUG_Generation(GenerationMixin)的 sample()链接的

### ISSUE THREAD

**Issue by zhangzhili1112** [RUC-NLPIR/FlashRAG#80]
我在sample()中增加了print("sample")，但并没有输出。
执行python3 run_exp.py --method_name=replug --dataset_name=nq --gpu_id=0 --split=test，同一个batch中的输出确实是一样的，
![image](https://github.com/user-attachments/assets/29fa36f3-b340-4ab8-bd95-b56cb17336bc)
所以想知道generate和sample怎么关联的

**Comment by ignorejjj** [comment]
generate和sample的关联代码得参考transformer的源代码中generate函数的实现: https://github.com/huggingface/transformers/blob/v4.44.1/src/transformers/generation/utils.py#L1588。

**Comment by zhangzhili1112** [comment]
(https://github.com/huggingface/transformers/blob/v4.44.1/src/transformers/generation/utils.py#L1588%E3%80%82)这个里面只有_sample()。
REPLUGLogitsProcessor可以确定是执行了，但是没法确定
class REPLUG_Generation(GenerationMixin):
    """Implementing REPLUG-based sampling text generation."""
    def sample()是否被调用
