### ISSUE TITLE
关于API调用

### ISSUE THREAD

**Issue by aJupyter** [RUC-NLPIR/FlashRAG#81]
请问如果我要自己封装一个LLM调用api
是不是只需要改generator部分就好？

**Comment by shadowworldqe** [comment]
是的，可以参考[openai_generator.py](https://github.com/RUC-NLPIR/FlashRAG/blob/main/flashrag/generator/openai_generator.py)。

**Comment by ignorejjj** [comment]
是的，可以参考[openai_generator.py](https://github.com/RUC-NLPIR/FlashRAG/blob/main/flashrag/generator/openai_generator.py).

**Comment by aJupyter** [comment]
> 是的，可以参考[openai_generator.py](https://github.com/RUC-NLPIR/FlashRAG/blob/main/flashrag/generator/openai_generator.py).

非常感谢，请问复现主实验的话
建立索引参数有需要变化的地方吗
`python -m flashrag.retriever.index_builder \
    --retrieval_method e5 \
    --model_path /model/e5-base-v2/ \
    --corpus_path indexes/sample_corpus.jsonl \
    --save_dir indexes/ \
    --use_fp16 \
    --max_length 200 \
    --batch_size 32 \
    --pooling_method mean \
    --faiss_type Flat `

**Comment by ignorejjj** [comment]
max_length需要设置到512，batch size可以开大点

**Comment by aJupyter** [comment]
> max_length需要设置到512，batch size可以开大点

参考这段话设置嘛
Retriever Setting: In our main experiments, we utilize [E5-base-v2](https://huggingface.co/intfloat/e5-base-v2) as the retriever, retrieving five documents per query. We use the DPR version of the Wikipedia December 2018 dataset as our retrieval corpus, which can be downloaded from our dataset hosting page [here](https://huggingface.co/datasets/ignore/FlashRAG_datasets). In subsequent retrieval experiments, we employ both BM25 and [bge-base-en-v1.5](https://huggingface.co/BAAI/bge-base-en-v1.5) as additional retrievers. The BM25 experiments are conducted using Pyserini. During index construction, the maximum padding length is set to 512, while the maximum query padding length is set to 128 during retrieval. The batch size for retrieval is 1024, with fp16 enabled. We employ the Faiss Flat index in indexing for accuracy.

**Comment by ignorejjj** [comment]
是的。需要注意的是如果用bge，需要把pooling method设置为cls

**Comment by aJupyter** [comment]
> 是的。需要注意的是如果用bge，需要把pooling method设置为cls

多谢！咱有没有什么交流群呀

**Comment by ignorejjj** [comment]
刚建了一个
![b6fec6ac235eeb091a3cdf58cfe4b06](https://github.com/user-attachments/assets/26f4a749-e3c7-49af-a3d3-20b5da7c9ba5)

**Comment by aJupyter** [comment]
多谢
