### ISSUE TITLE
主表中zero-shot的复现效果相差很多

### ISSUE THREAD

**Issue by liuchengyuan123** [RUC-NLPIR/FlashRAG#85]
您好！感谢您对此项目的贡献和一直以来非常及时的回复！

我尝试用Meta-Llama3-8B-Instruct模型复现表格中不加retrieve的结果，这样不受到retrieve相关参数的区别的影响。
但是我的结果与表格中相差很多，具体来说：

|nq|triviaqa|hotpotqa|
|-|-|-|
|19.00|47.60|23.06|

我用vllm框架在4*A100 GPUs上进行实验。使用了前1000条的数据进行测试，用vllm框架进行的generation。其他参数都和my_config设置的相同。一个hotpotqa的prompt如下：
```text
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

Answer the question based on your own knowledge. Only give me the answer and do not output any other words.<|eot_id|><|start_header_id|>user<|end_header_id|>

Question: Were Scott Derrickson and Ed Wood of the same nationality?<|eot_id|><|start_header_id|>assistant<|end_header_id|>
```

请问是否有经验关于为何效果会和表中相差很多？

十分感谢！！

**Comment by liuchengyuan123** [comment]
我发现换成hf替代vllm，生成效果更接近README中的结果了。不过这个差距好像还不在误差范围内。
|nq|triviaqa|hotpotqa|
|-|-|-|
|21.80|51.90|26.44|

**Comment by ignorejjj** [comment]
差距在两个点左右，感觉是机器直接随机性的影响。可以尝试把do_sample设置为True，看一下结果是否有优化。


---- 回复的原邮件 ----
发件人  ***@***.***> 日期  2024年09月15日 09:45 收件人  ***@***.***> 抄送至  ***@***.***> 主题  Re: [RUC-NLPIR/FlashRAG] 主表中zero-shot的复现效果相差很多 (Issue #85)  

我发现换成hf替代vllm，生成效果更接近README中的结果了。不过这个差距好像还不在误差范围内。
nq triviaqa hotpotqa21.80  51.90  26.44  —

**Comment by liuchengyuan123** [comment]
好的，谢谢。我发现vllm原始的设置需要加上一个"temperature=0"来关掉采样，这样vllm和hf的结果基本一致了。

**Comment by Rinnolo** [comment]
> 好的，谢谢。我发现vllm原始的设置需要加上一个"temperature=0"来关掉采样，这样vllm和hf的结果基本一致了。

我也发现了欸，理论上`do_sample=false`的话是不需要特地加上`temperature=0`吧。

**Comment by ignorejjj** [comment]
> > 好的，谢谢。我发现vllm原始的设置需要加上一个"temperature=0"来关掉采样，这样vllm和hf的结果基本一致了。
> 
> 我也发现了欸，理论上`do_sample=false`的话是不需要特地加上`temperature=0`吧。

之前vllm的设置参数有点问题，现在已经修复
