### ISSUE TITLE
use_retrieval_cache无法正常使用的问题

### ISSUE THREAD

**Issue by Arkcy** [RUC-NLPIR/FlashRAG#86]
您好！感谢您在此项目中的付出！
我在调用SuRe在popqa上测试时，尝试使用了use_retrieval_cache为True的设置（使用的retrieval_cache.json是之前设置save_retrieval_cache为True时生成的），但遇到了如下的报错（KeyError: 'score'）：

`[rank0]: Traceback (most recent call last):`
`[rank0]:   File "/.../FlashRAG/exp_popqal.py", line 587, in <module>`
`[rank0]:     func(args)`
`[rank0]:   File "/.../FlashRAG/exp_popqa.py", line 270, in sure`
`[rank0]:     result = pipeline.run(test_data)`
`[rank0]:   File "/.../FlashRAG/flashrag/pipeline/branching_pipeline.py", line 170, in run`
`[rank0]:     retrieval_results, doc_scores = self.retriever.batch_search(input_query, return_score=True)`
`[rank0]:   File "/.../FlashRAG/flashrag/retriever/retriever.py", line 42, in wrapper`
`[rank0]:     doc_scores = [item.pop("score") for item in cache_res]`
`[rank0]:   File "/.../FlashRAG/flashrag/retriever/retriever.py", line 42, in <listcomp>`
`[rank0]:     doc_scores = [item.pop("score") for item in cache_res]`
`[rank0]: KeyError: 'score'`
`ERROR 09-24 17:10:06 multiproc_worker_utils.py:120] Worker VllmWorkerProcess pid 34097 died, exit code: -15`
`INFO 09-24 17:10:06 multiproc_worker_utils.py:123] Killing local vLLM worker processes`

在打印中间结果cache_res后，发现代码可以在前几百个question上正常运行，但会突然在某一个cache_res中遇到dict不含‘score’的key的情况。
以下是该cache_res展开后的结果，可以看到这一个cache_res里所有dict全都不含‘score’：
![01](https://github.com/user-attachments/assets/9e9423e7-e579-445c-9a41-80643381cf2b)

查找retrieval_cache.json后发现，本来是没有这个问题的，cache中是正常含有score的：
![02](https://github.com/user-attachments/assets/a63419b1-48d3-4cef-bb4b-7616308212ef)

也就是说retrieval_cache.json中本含有的score项在运行过程中突然没有了，怀疑是代码可能存在bug。
能否请您排查一下，非常感谢！！

**Comment by ignorejjj** [comment]
排查过后发现可能是原先的`doc_scores`读取过程中使用了`pop`进行score的取出，导致第二次检索到相同的文档会出现没有score的情况。已经在commit a8e41c25a2379bd01008837e6244c57c629d796f 中进行了修复，请更新代码后再进行尝试。

**Comment by Arkcy** [comment]
更新代码后测试不再报错，问题解决，感谢您的帮助！
