### ISSUE TITLE
replug复现时遇到问题

### ISSUE THREAD

**Issue by Arkcy** [RUC-NLPIR/FlashRAG#87]
您好！感谢您在此项目中的付出！
我在调用replug框架在popqa上测试时的时候报出了如下错误（同样的设置测试sure能够正常运行）：

 ` Traceback (most recent call last):`
`  File "/.../FlashRAG/exp_popqa.py", line 589, in <module>`
`    func(args)`
`  File "/.../FlashRAG/exp_popqa.py", line 291, in replug`
`    pipeline = REPLUGPipeline(config)`
`  File "/.../FlashRAG/flashrag/pipeline/branching_pipeline.py", line 19, in __init__`
`    self.generator = get_generator(config, model=model)`
`  File "/.../FlashRAG/flashrag/utils/utils.py", line 33, in get_generator`
`    return getattr(importlib.import_module("flashrag.generator"), "VLLMGenerator")(config, **params)`
`TypeError: __init__() got an unexpected keyword argument 'model'`

请问是replug的pipeline需要进行其他的特殊设置吗？我在文档中并没有找到相应的内容，能否麻烦您解答一下，非常感谢！！

**Comment by ignorejjj** [comment]
replug方法需要在生成端对logits做自定义处理，目前不支持使用VLLM作为generator，换成剩下的generator框架就行。

**Comment by Arkcy** [comment]
感谢您的解答，问题已解决
